export const TipoDocumento = {
    HABILITACION_MUNICIPAL: 'HABILITACION_MUNICIPAL',
    FOTO_FRENTE: 'FOTO_FRENTE',
    FOTO_INTERIOR: 'FOTO_INTERIOR',
    COMPROBANTE_DOMICILIO: 'COMPROBANTE_DOMICILIO',
    CONSTANCIA_FISCAL: 'CONSTANCIA_FISCAL',
};
